app = "bottg1"
primary_region = "fra"  # Измените на ваш регион

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true

# Критически важно - ограничиваем до 1 экземпляра
[processes]
  app = "python main.py"

[processes.app.concurrency]
  hard_limit = 1
  soft_limit = 1

[deploy]
  strategy = "immediate"
  health_check_timeout = 10