app = "bottg1"  
primary_region = "iad"  # или "fra", "ams" и т.д.  

[build]  
  image = "python:3.11-slim"  

[env]  
  PYTHONUNBUFFERED = "1"  
  PYTHONFAULTHANDLER = "1"  

[http_service]  
  internal_port = 8080  
  force_https = true  
  auto_stop_machines = false  # чтобы бот не останавливался  

  [[http_service.ports]]  
    handlers = ["http"]  
    port = 80  
  [[http_service.ports]]  
    handlers = ["tls", "http"]  
    port = 443  

[machine]  
  cpus = 1  
  memory = "512mb"  