app = "bottg1"
primary_region = "iad"

[build]
  image = "python:3.11-slim"
  builder = "paketobuildpacks/builder:base"

[deploy]
  strategy = "rolling"
  wait_timeout = 120  # Увеличиваем таймаут до 120 секунд

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false

[machine]
  cpus = 1
  memory = "512mb"
  guest = { cpus = 1, memory_mb = 512 }