[app]
  name = "bottg1"
  primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true

[env]
  TELEGRAM_TOKEN = "ваш_токен_бота"
  FLY_APP_NAME = "bottg1"

[deploy]
  strategy = "immediate"