[app]
  name = "bottg1"
  primary_region = "fra"  # Или ваш регион (lax, syd, etc)

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true

[processes]
  app = "python main.py"

  [processes.app.concurrency]
    hard_limit = 1
    soft_limit = 1

[deploy]
  strategy = "immediate"