app = "bottg1"
primary_region = "ams"

[build]
  image = "python:3.11-slim"

[env]
  PYTHONUNBUFFERED = "1"
  PYTHONFAULTHANDLER = "1"

[http_service]
  internal_port = 8080  # Для вебхука
  force_https = true
  auto_stop_machines = false

[[services]]
  internal_port = 8081  # Для Flask
  protocol = "tcp"

[machine]
  cpus = 1
  memory = "512mb"