app = "bottg1"
primary_region = "fra"

[build]
  builder = "dockerfile"
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"
  build_args = { PYTHON_VERSION = "3.11" }  # Явное указание версии Python

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PYTHONUNBUFFERED = "1"
  PORT = "8080"
  PYTHONDONTWRITEBYTECODE = "1"
  PYTHONFAULTHANDLER = "1"  # Для отладки критических ошибок

[deploy]
  strategy = "rolling"
  max_unavailable = 0  # Гарантирует нулевое время простоя при деплое

[vm]
  memory = "512mb"  # Оптимально для Python-бота
  cpus = 1  # Достаточно для большинства ботов