app = "bottg1"  # Название должно точно совпадать с созданным в fly.io

[build]
  image = "python:3.9-slim"  # Более стабильная версия для Telegram ботов
  # builder = "paketobuildpacks/builder:base"  # Убрано - используем стандартную сборку

[env]
  PYTHONUNBUFFERED = "1"  # Для корректного вывода логов
  PYTHONFAULTHANDLER = "1"  # Для детализации ошибок

# Секреты устанавливаются через:
# flyctl secrets set TELEGRAM_TOKEN=your_token_here

[http_service]
  internal_port = 8080  # Должен совпадать с портом в коде бота
  force_https = true    # Обязательно для работы с Telegram API
  auto_stop_machines = true  # Лучше true для экономии ресурсов

[deploy]
  strategy = "rolling"  # Плавные обновления без downtime
  # release_command удален - установка зависимостей происходит автоматически