app = "your-app-name"
primary_region = "fra"  # Например, Frankfurt (fra)

[build]
  builder = "dockerfile"
  dockerfile = "Dockerfile"

[env]
  TELEGRAM_TOKEN = "8141115973:AAF8q3jQHDAzN2y-siISPTCtr9-EM3wEYgU"  # Или используйте `fly secrets set`

[http_service]
  internal_port = 8080
  force_https = true